# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(1035, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(1035, 750))
        self.label_title = QtWidgets.QLabel(Form)
        self.label_title.setGeometry(QtCore.QRect(380, 10, 271, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_image_preview = QtWidgets.QLabel(Form)
        self.label_image_preview.setGeometry(QtCore.QRect(10, 100, 500, 400))
        self.label_image_preview.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_preview.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_image_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_preview.setObjectName("label_image_preview")
        self.label_image_capture = QtWidgets.QLabel(Form)
        self.label_image_capture.setGeometry(QtCore.QRect(520, 100, 500, 400))
        self.label_image_capture.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_capture.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_image_capture.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_capture.setObjectName("label_image_capture")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 70, 91, 16))
        self.label.setObjectName("label")
        self.label_status = QtWidgets.QLabel(Form)
        self.label_status.setGeometry(QtCore.QRect(820, 55, 191, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_status.setFont(font)
        self.label_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_status.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.label_trigger_value = QtWidgets.QLabel(Form)
        self.label_trigger_value.setGeometry(QtCore.QRect(560, 60, 201, 31))
        self.label_trigger_value.setObjectName("label_trigger_value")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 520, 200, 201))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_video_cap = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_video_cap.setGeometry(QtCore.QRect(40, 110, 120, 60))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.pushButton_video_cap.setFont(font)
        self.pushButton_video_cap.setObjectName("pushButton_video_cap")
        self.pushButton_open_file = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_open_file.setGeometry(QtCore.QRect(40, 40, 120, 60))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.pushButton_open_file.setFont(font)
        self.pushButton_open_file.setObjectName("pushButton_open_file")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(240, 520, 411, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textBrowser_debug = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowser_debug.setGeometry(QtCore.QRect(10, 20, 161, 171))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(7)
        self.textBrowser_debug.setFont(font)
        self.textBrowser_debug.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser_debug.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_debug.setObjectName("textBrowser_debug")
        self.label_good_info = QtWidgets.QLabel(self.groupBox_2)
        self.label_good_info.setGeometry(QtCore.QRect(190, 20, 211, 171))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_good_info.setFont(font)
        self.label_good_info.setFrameShape(QtWidgets.QFrame.Box)
        self.label_good_info.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_good_info.setText("")
        self.label_good_info.setObjectName("label_good_info")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(660, 520, 331, 201))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_calc = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_calc.setGeometry(QtCore.QRect(50, 30, 101, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_calc.setFont(font)
        self.pushButton_calc.setDefault(True)
        self.pushButton_calc.setObjectName("pushButton_calc")
        self.pushButton_cancel = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_cancel.setGeometry(QtCore.QRect(180, 30, 101, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setDefault(False)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.label_price = QtWidgets.QLabel(self.groupBox_3)
        self.label_price.setGeometry(QtCore.QRect(20, 110, 291, 61))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_price.setFont(font)
        self.label_price.setFrameShape(QtWidgets.QFrame.Box)
        self.label_price.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_price.setObjectName("label_price")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "商品检测"))
        self.label_title.setText(_translate("Form", "商品结算控制台"))
        self.label_image_preview.setText(_translate("Form", "预览"))
        self.label_image_capture.setText(_translate("Form", "抓拍"))
        self.label.setText(_translate("Form", "摄像头预览："))
        self.label_trigger_value.setText(_translate("Form", "抓拍触发阈值："))
        self.groupBox.setTitle(_translate("Form", "模式切换"))
        self.pushButton_video_cap.setText(_translate("Form", "摄像头采集通道"))
        self.pushButton_open_file.setText(_translate("Form", "使用图片识别"))
        self.groupBox_2.setTitle(_translate("Form", "识别结果"))
        self.groupBox_3.setTitle(_translate("Form", "购买计价"))
        self.pushButton_calc.setText(_translate("Form", "计价"))
        self.pushButton_cancel.setText(_translate("Form", "清零"))
        self.label_price.setText(_translate("Form", "总价：0元"))

